export const LOGIN_IN = 'login_in'
export const LOGIN_OUT = 'login_out'
export const SET_TOKEN = 'set_token'
export const RESET_USER_STATE = 'reset_user_state'
export const SET_USER_INFO = 'set_user_info'
export const REGISTER_SUCC = 'register_succ'